CLASS zcl_lab_39_budget_noa DEFINITION
  PUBLIC
  ABSTRACT
  CREATE PUBLIC.

  PUBLIC SECTION.
    METHODS:
      get_budget ABSTRACT RETURNING VALUE(rv_budget) TYPE string.
ENDCLASS.



CLASS zcl_lab_39_budget_noa IMPLEMENTATION.
ENDCLASS.
